name: release

on:
    workflow_dispatch


jobs:
  release:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: janbizongd/spring-petclinic
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: host.docker.internal:9903
          username: ${{ vars.NEXUS_USER }}
          password: ${{ secrets.NEXUS_SECRET }}
      - name: prepare_release
        run: |
          ./gradlew createRelease 
      - name: docker build
        run: |
          docker images
          docker build -t host.docker.internal:9903/main:$(./gradlew cV -q -Prelease.quiet) .
          docker push host.docker.internal:9903/main:$(./gradlew cV -q -Prelease.quiet)
# later version should be increased and pushed to github
